services:
  mysql-db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: traffic-one
      MYSQL_USER: jaeha
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
